default:
  server:
    plugin: "AsyncSshServer"
    configuration:
      address: "0.0.0.0"
      timeout: 1

hosts:
  router:
    username: user
    password: user
    port:
    - 6001
    - 6002
    replicas: 2
    device_type: cisco_ios
